# Generated by Django 3.1.3 on 2020-11-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Censo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idestado', models.TextField(blank=True)),
                ('estado', models.TextField(blank=True)),
                ('idmunicipio', models.TextField(blank=True)),
                ('municipio', models.TextField(blank=True)),
                ('actividad', models.TextField(blank=True)),
                ('UE', models.DecimalField(decimal_places=4, max_digits=20)),
                ('H001A', models.DecimalField(decimal_places=4, max_digits=20)),
                ('H010A', models.DecimalField(decimal_places=4, max_digits=20)),
                ('A111A', models.DecimalField(decimal_places=4, max_digits=20)),
                ('A211A', models.DecimalField(decimal_places=4, max_digits=20)),
                ('M091A', models.DecimalField(decimal_places=4, max_digits=20)),
                ('H010D', models.DecimalField(decimal_places=4, max_digits=20)),
                ('H020A', models.DecimalField(decimal_places=4, max_digits=20)),
                ('I000A', models.DecimalField(decimal_places=4, max_digits=20)),
                ('I100A', models.DecimalField(decimal_places=4, max_digits=20)),
                ('I200A', models.DecimalField(decimal_places=4, max_digits=20)),
                ('K000A', models.DecimalField(decimal_places=4, max_digits=20)),
                ('K020A', models.DecimalField(decimal_places=4, max_digits=20)),
                ('K311A', models.DecimalField(decimal_places=4, max_digits=20)),
                ('K040A', models.DecimalField(decimal_places=4, max_digits=20)),
                ('K041A', models.DecimalField(decimal_places=4, max_digits=20)),
                ('K050A', models.DecimalField(decimal_places=4, max_digits=20)),
                ('K620A', models.DecimalField(decimal_places=4, max_digits=20)),
                ('K060A', models.DecimalField(decimal_places=4, max_digits=20)),
                ('K810A', models.DecimalField(decimal_places=4, max_digits=20)),
                ('K090A', models.DecimalField(decimal_places=4, max_digits=20)),
                ('A700A', models.DecimalField(decimal_places=4, max_digits=20)),
                ('M000A', models.DecimalField(decimal_places=4, max_digits=20)),
                ('M020A', models.DecimalField(decimal_places=4, max_digits=20)),
                ('M090A', models.DecimalField(decimal_places=4, max_digits=20)),
                ('A800A', models.DecimalField(decimal_places=4, max_digits=20)),
            ],
        ),
    ]
